"""empty message

Revision ID: 5dccf849b1aa
Revises: 13dd3914e8d9
Create Date: 2022-05-11 14:16:22.613874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dccf849b1aa'
down_revision = '13dd3914e8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dob', sa.String(length=10), nullable=False))
    op.add_column('user', sa.Column('first_name', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=40), nullable=False))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'dob')
    # ### end Alembic commands ###
